# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Added for REST Api Integration for OpenDTU
# The integration name "rest:" must appear hear, but belongs to the opendtu.yaml
rest: !include_dir_merge_list opendtu/

# Add cloudflare for VPN Tunnel using cloudflared add-on
# The trusted proxy is the local docker network
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
