# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Added for REST Api Integration for OpenDTU
# The integration name "rest:" must appear hear, but belongs to the opendtu.yaml
rest: !include opendtu.yaml
